import "antd/dist/reset.css";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./(navbar)/Navbar";
import Footer from "./components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${poppins?.variable} antialiased`}>
        <Navbar />
        <div className="w-11/12 mx-auto min-h-[calc(100vh-284px)]">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
